### ISSUE TITLE
Proliant Gen11 problem with cpu and drive status

### ISSUE THREAD

**Issue by erSitzt** [lausser/check_hpasm#28]
Hi, not sure if this is still actively maintained but anyway :)

Gen11  Proliant reports the following

CRITICAL - cpu 1 needs attention (failed), physical drive 1:1 is other, physical drive 1:2 is other, System: 'proliant dl380 gen11', S/N: 'CZ23250HWX', ROM: 'U54 v1.30'

This is an VMware ESXi host and neither iLO nor VMware itself are reporting any issues.

We have two other identical Gen11, all of them are reporting the drives as "other", only one thinks the CPU failed.
These are Intel(R) Xeon(R) Gold 6458Q CPUs, where cores can be disabled to increase the CPU base frequency.
32 cores => 3Ghz
24 cores => 3,5Ghz
16 cores => 4Ghz

This one is configured with 24 cores, so 8 are disabled
The one with 16 cores does not have a problem with the cpu according to check_hpasm

I did not yet check the snmp output, but i can provide it if needed

**Comment by erSitzt** [comment]
@fragfutter thanks for the drive status fix

@lausser 
The CPU issue still remains with the current version

**Comment by erSitzt** [comment]
ILO has nothing to complain about

<img width="1026" alt="image" src="https://github.com/lausser/check_hpasm/assets/1625376/a9186a5c-bd93-4dc4-8fbc-137d68e2baca">


<img width="933" alt="image" src="https://github.com/lausser/check_hpasm/assets/1625376/46b67bfe-ba4f-427e-b356-9f99f882ef55">

**Comment by lausser** [comment]
When the plugin says: cpu has status "failed", then it only repeats the value of the OID. When you run an snmpwalk against this ILO, you will surely see the "failed" as well.
